#!/bin/bash

#(i)
sed -n '/and/p' python.txt

#(ii)
sed 's/language/lang/g' python.txt

#(iii)
sed 's/is/d' python.txt

#(iv)
sed '=' python.txt | sed 'N;s/\n/ /'

#(v)
sed '1,2d' python.txt

#(vi)
sed -n '1~2p' python.txt

#(vii)
sed 's/Python/python/ ; s/language/lang/' python.txt

